import React from "react"
import { Checkbox } from "./checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/2CsBqIj6tkircEZhCTg594/Design-system---Components?node-id=195%3A2931",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checked: figma.enum("Checked", {
        False: false,
        True: true,
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "labelText": figma.string('Label text'),
      // "indeterminate": figma.boolean('Indeterminate')
    },
    example: (props) => (
      <Checkbox checked={props.checked} disabled={props.disabled} />
    ),
  },
)
