import React from "react"
import { FilterButton } from "./filter-button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  FilterButton,
  "https://www.figma.com/design/2CsBqIj6tkircEZhCTg594/Design-system---Components?node-id=1042%3A6652",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.boolean("Disabled"),
      // No matching props could be found for these Figma properties:
      // "numberText": figma.string('Number text')
    },
    example: (props) => (
      <FilterButton label={/* TODO */} disabled={props.disabled} />
    ),
  },
)
