import React from "react"
import { Footer } from "./footer"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Footer,
  "https://www.figma.com/design/2CsBqIj6tkircEZhCTg594/Design-system---Components?node-id=3353%3A238",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "viewport": figma.enum('Viewport', {
      //   "Desktop": "desktop",
      //   "Tablet": "tablet",
      //   "Mobile": "mobile"
      // })
    },
    example: (props) => <Footer />,
  },
)
