import React from "react"
import { Tooltip } from "./tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/2CsBqIj6tkircEZhCTg594/Design-system---Components?node-id=105%3A1738",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "tooltipText": figma.string('Tooltip text'),
      // "position": figma.enum('Position', {
      //   "Bottom": "bottom",
      //   "Top": "top",
      //   "Left": "left",
      //   "Right": "right"
      // }),
      // "alignment": figma.enum('Alignment', {
      //   "Centred": "centred",
      //   "Left": "left",
      //   "Right": "right"
      // })
    },
    example: (props) => <Tooltip />,
  },
)
